name: Compile CoercedPotato

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone CoercedPotato repository
      run: git clone https://github.com/Prepouce/CoercedPotato.git

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install dependencies
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Build with MSBuild
      run: msbuild CoercedPotato/CoercedPotato.sln /p:Configuration=Release

    - name: Post build - list files
      run: dir CoercedPotato\x64\Release

    - name: Verify executable
      run: |
        if exist CoercedPotato\x64\Release\CoercedPotato.exe (
          echo "Build successful: CoercedPotato.exe found."
        ) else (
          echo "Build failed: CoercedPotato.exe not found."
          exit 1
        )
